In [21]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
import pickle

In [22]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [23]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1,)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [24]:
## encode the gender column using label encoder

le_gender=LabelEncoder()
data['Gender']=le_gender.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [25]:
## One hot encoding for the 'Geography' column
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
geo_encoder = encoder.fit_transform(data[['Geography']])
feature_names = encoder.get_feature_names_out(['Geography'])

print(feature_names)
print(geo_encoder)

['Geography_France' 'Geography_Germany' 'Geography_Spain']
[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]

In [26]:
geo_encoded_df = pd.DataFrame(geo_encoder, columns=feature_names)
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [27]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [28]:
## combine the encoded columns with the original dataframe

data=pd.concat([data.drop(columns=['Geography']), geo_encoded_df], axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [29]:
## divide the data into features (independent variables) and target variable(dependent variable)
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

## split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [30]:
X_train.shape

(8000, 12)

In [31]:
X_train, x_val, y_train, y_val = train_test_split(
    X_train,
    y_train,
    test_size=0.2,
    random_state=0
)

In [32]:
X_train.shape,x_val.shape,y_train.shape,y_val.shape

((6400, 12), (1600, 12), (6400,), (1600,))

In [33]:
X_train

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
9031,541,1,39,7,0.00,2,1,0,0,1.0,0.0,0.0
9160,778,1,24,4,0.00,2,1,1,0,1.0,0.0,0.0
175,484,0,35,7,133868.21,1,1,1,0,0.0,0.0,1.0
9112,735,1,73,9,0.00,1,1,1,0,1.0,0.0,0.0
9324,780,1,71,9,142550.25,2,1,1,0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8111,560,0,31,3,115141.18,1,1,0,0,1.0,0.0,0.0
7966,677,0,34,4,0.00,2,1,1,0,0.0,0.0,1.0
9729,651,1,23,10,0.00,2,1,1,0,1.0,0.0,0.0
6621,646,1,50,0,104129.24,2,1,0,1,1.0,0.0,0.0
2966,511,1,45,5,68375.27,1,1,0,1,1.0,0.0,0.0

In [34]:
## Scale the features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
x_val = scaler.transform(x_val)
X_test = scaler.transform(X_test)

In [35]:
X_train

array([[-1.1302282 ,  0.9148601 ,  0.00212983, ...,  0.97530483,
        -0.5658021 , -0.56965192],
       [ 1.3106727 ,  0.9148601 , -1.42768856, ...,  0.97530483,
        -0.5658021 , -0.56965192],
       [-1.71728032, -1.0930633 , -0.37915507, ..., -1.02532046,
        -0.5658021 ,  1.75545796],
       ...,
       [ 0.00267939,  0.9148601 , -1.52300979, ...,  0.97530483,
        -0.5658021 , -0.56965192],
       [-0.04881641,  0.9148601 ,  1.05066333, ...,  0.97530483,
        -0.5658021 , -0.56965192],
       [-1.439203  ,  0.9148601 ,  0.57405719, ...,  0.97530483,
        -0.5658021 , -0.56965192]])

In [36]:
## save the encoder and scalar
with open('onehot_encoder_geo_salary.pkl', 'wb') as f:
    pickle.dump(encoder, f)
with open('label_encoder_gender_salary.pkl', 'wb') as f:
    pickle.dump(le_gender, f)
with open('scaler_salary.pkl', 'wb') as f:
    pickle.dump(scaler, f)

## ANN Implementation

## ANN Architecture

1. BUILD   
   ↓  
   model = Sequential(...)  

2. COMPILE  
   ↓  
   model.compile(...)  
   
3. TRAIN   
   ↓  
   model.fit(...)  
  
4. PREDICT  
   ↓  
   model.predict(...)

In [37]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

WARNING:tensorflow:From e:\ANN classification\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

## 1. BUILD

In [39]:
## Build the ANN model
salary_model= Sequential()
salary_model.add(Dense(units=64, activation='relu', input_dim=12))
salary_model.add(Dense(units=32, activation='relu'))
salary_model.add(Dense(units=1,))

In [40]:
salary_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

## 2. COMPILE

In [41]:
## compile the model
salary_model.compile(optimizer='adam', loss="mae", metrics=['mae'])

WARNING:tensorflow:From e:\ANN classification\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

### 3. TRAIN

In [43]:
## set up TensorBoard callback
log_dir = "logs/fit/salaryregression_/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

In [44]:
## set up EarlyStopping callback to prevent overfitting and stop training when the validation loss stops improving
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

In [47]:
model_history = salary_model.fit(
    X_train,
    y_train,
    epochs=500,
    validation_data=(x_val, y_val),
    callbacks=[tensorboard_callback, early_stopping]
)

Epoch 1/500
200/200 [==============================] - 1s 3ms/step - loss: 49316.4258 - mae: 49316.4258 - val_loss: 50023.7266 - val_mae: 50023.7266
Epoch 2/500
200/200 [==============================] - 0s 2ms/step - loss: 49309.5039 - mae: 49309.5039 - val_loss: 50024.6992 - val_mae: 50024.6992
Epoch 3/500
200/200 [==============================] - 1s 3ms/step - loss: 49310.3086 - mae: 49310.3086 - val_loss: 50012.5586 - val_mae: 50012.5586
Epoch 4/500
200/200 [==============================] - 1s 3ms/step - loss: 49307.2891 - mae: 49307.2891 - val_loss: 50020.2109 - val_mae: 50020.2109
Epoch 5/500
200/200 [==============================] - 1s 3ms/step - loss: 49302.8359 - mae: 49302.8359 - val_loss: 50022.5547 - val_mae: 50022.5547
Epoch 6/500
200/200 [==============================] - 1s 3ms/step - loss: 49300.9414 - mae: 49300.9414 - val_loss: 50016.7305 - val_mae: 50016.7305
Epoch 7/500
200/200 [==============================] - 0s 2ms/step - loss: 49299.9766 - mae: 49299.9766 - val_loss: 50019.8867 - val_mae: 50019.8867
Epoch 8/500
200/200 [==============================] - 0s 2ms/step - loss: 49293.9648 - mae: 49293.9648 - val_loss: 50015.5195 - val_mae: 50015.5195
Epoch 9/500
200/200 [==============================] - 0s 2ms/step - loss: 49293.8398 - mae: 49293.8398 - val_loss: 50017.1602 - val_mae: 50017.1602
Epoch 10/500
200/200 [==============================] - 0s 2ms/step - loss: 49290.2344 - mae: 49290.2344 - val_loss: 50018.2305 - val_mae: 50018.2305
Epoch 11/500
200/200 [==============================] - 0s 2ms/step - loss: 49287.7461 - mae: 49287.7461 - val_loss: 50020.3359 - val_mae: 50020.3359
Epoch 12/500
200/200 [==============================] - 0s 2ms/step - loss: 49287.7031 - mae: 49287.7031 - val_loss: 50008.7188 - val_mae: 50008.7188
Epoch 13/500
200/200 [==============================] - 1s 3ms/step - loss: 49285.6953 - mae: 49285.6953 - val_loss: 50023.5508 - val_mae: 50023.5508
Epoch 14/500
200/200 [==============================] - 1s 3ms/step - loss: 49281.2383 - mae: 49281.2383 - val_loss: 50018.1992 - val_mae: 50018.1992
Epoch 15/500
200/200 [==============================] - 0s 2ms/step - loss: 49278.9414 - mae: 49278.9414 - val_loss: 50020.4336 - val_mae: 50020.4336
Epoch 16/500
200/200 [==============================] - 0s 2ms/step - loss: 49275.2266 - mae: 49275.2266 - val_loss: 50033.5000 - val_mae: 50033.5000
Epoch 17/500
200/200 [==============================] - 1s 4ms/step - loss: 49274.6484 - mae: 49274.6484 - val_loss: 50030.0156 - val_mae: 50030.0156
Epoch 18/500
200/200 [==============================] - 1s 3ms/step - loss: 49268.9766 - mae: 49268.9766 - val_loss: 50024.8203 - val_mae: 50024.8203
Epoch 19/500
200/200 [==============================] - 0s 2ms/step - loss: 49272.1484 - mae: 49272.1484 - val_loss: 50015.9688 - val_mae: 50015.9688
Epoch 20/500
200/200 [==============================] - 1s 3ms/step - loss: 49264.5781 - mae: 49264.5781 - val_loss: 50015.6289 - val_mae: 50015.6289
Epoch 21/500
200/200 [==============================] - 1s 3ms/step - loss: 49267.0117 - mae: 49267.0117 - val_loss: 50027.9883 - val_mae: 50027.9883
Epoch 22/500
200/200 [==============================] - 1s 3ms/step - loss: 49261.9141 - mae: 49261.9141 - val_loss: 50021.9844 - val_mae: 50021.9844

In [48]:
salary_model.save('salary_model.h5')

e:\ANN classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [52]:
## Load TensorBoard Extension in Jupyter Notebook
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [55]:
%tensorboard --logdir logs/fit/salaryregression_/

Reusing TensorBoard on port 6008 (pid 34312), started 0:00:05 ago. (Use '!kill 34312' to kill it.)

### 4. PREDICT

In [56]:
# evaluate the model on the test set
test_loss, test_mae = salary_model.evaluate(X_test, y_test)
print(f"Test Loss: {test_loss}, Test MAE: {test_mae}")

63/63 [==============================] - 0s 1ms/step - loss: 49906.7227 - mae: 49906.7227
Test Loss: 49906.72265625, Test MAE: 49906.72265625